# -*- coding: utf-8 -*-
"""CFER_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5pmoajTAMKU9FicWYPf_KoiTK1qsWqT
"""

!pip install pdfplumber -q
!pip install requests

#importing libraries
import pdfplumber
from google.colab import drive
import os
import requests
import pdfplumber
import pandas as pd

# Step 1: Download the PDF
url = "https://resources.finalsite.net/images/v1694219355/sdcoenet/yzchqgsx1spvuioffpp7/2023-24-Poway.pdf"
response = requests.get(url)

# Step 2: Save the PDF to a temporary file
with open("temp.pdf", "wb") as f:
    f.write(response.content)

# Step 3: Open the saved PDF using pdfplumber
pages = []
start_phrase = "Goals and Actions"
end_phrase = "Total Expenditures Table"
collecting = False

with pdfplumber.open("temp.pdf") as pdf:
    # Step 4: Extract text from each page
    for page in pdf.pages:
        text = page.extract_text()

        if (start_phrase in text):
          collecting = True

        if (collecting):
          pages.append(text)
          table = page.extract_table()

          # If a table is found, process it
          if table and page.page_number == 29:
              print(f'Table found on page {page.page_number}:')
              for row in table:
                  print(row)
              break
        if (end_phrase in text):
          break

# After extracting the table
if table:
    df = pd.DataFrame(table[1:], columns=table[0])  # First row as headers
    df = df.iloc[:,:-2]
    print(df)

